### ISSUE TITLE
One Question

### ISSUE THREAD

**Issue by Heus-Sueh** [hwittenborn/makedeb#250]
### Description of feature

![image](https://user-images.githubusercontent.com/98482469/214923412-75409d78-d833-423a-b14b-1693786ba948.png)
can makedeb install the .deb like pacstall?

### Installed makedeb version

makedeb 6.0.0-stable Stable Release Installed from APT

**Comment by hwittenborn** [comment]
I've thought about this for a while. Originally I was against it but you're not the first person to complain about the issue so I'm getting a bit interested in implementing this somehow.

I'm not sure if I want this in makedeb itself - I'm mostly viewing makedeb as just a build tool right now, and having it just directly install the deb like Pacstall makes makedeb feel just like an APT wrapper to me, and that's not really a view I've ever had for it.

Would you be fine if such behavior was handled by [Mist](https://docs.makedeb.org/using-the-mpr/mist-the-mpr-cli/) though? I'd be more fine adding it there since that's more of an APT wrapper - I'm thinking it could be handled like how Nala handles it where you could just run this (note that this won't currently work with Mist):

```sh
mist install 'https://deb.librewolf.../librewolf.deb'
```

makedeb's extension system could also make this process work directly with makedeb itself, though the extension system hasn't been documented much yet. I can give more info on that if you'd want it though.

Which approach would you prefer most? If not those, do you have any others in mind? I'm definitely interested in getting this happening in one way or the other since there appears to be demand for it.

**Comment by Heus-Sueh** [comment]
> Would you be fine if such behavior was handled by [Mist](https://docs.makedeb.org/using-the-mpr/mist-the-mpr-cli/) though? I'd be more fine adding it there since that's more of an APT wrapper - I'm thinking it could be handled like how Nala handles it where you could just run this (note that this won't currently work with Mist):

Honestly I don't know, an extension of makedeb would be perhaps the best option

The problem of Debian, Ubuntu, Linux Mint ... is that the most "popular" programs are in the repositories of Github, Gitlab, Sourcehut and Codeberg, You can hardly install a program without installing another repository

> Would you be fine if such behavior was handled by [Mist](https://docs.makedeb.org/using-the-mpr/mist-the-mpr-cli/) though? I'd be more fine adding it there since that's more of an APT wrapper - I'm thinking it could be handled like how Nala handles it where you could just run this (note that this won't currently work with Mist):

Seeing this proposal again, if the Mist could do this would facilitate the installation of a program with just one command, it would partially solve the above problem

But the final solution would be the same as that of AUR, a only repository linking all other decentralized repositories

**Comment by hwittenborn** [comment]
Sorry for the delayed response, I've got a lot of GitHub notifications I've yet to clear up and this got a bit lost amongst all of them.

> Honestly I don't know, an extension of makedeb would be perhaps the best option

If that approach were to be done, the resulting PKGBUILD might look something like this:

```sh
# Maintainer: Foo Bar <foobar@example.com>
pkgname=librewolf-deb
...
extensions=('deb-packager')
source=('https://.../librewolf.deb')

package() {
    makedeb-deb-packager librewolf.deb
}
```

It's a bit more than what you might have to type with something like Pacstall, but would that be acceptable for you? Or are you more so wanting the way Pacstall does it?

By the way, this is just a question related to ease-of-use in creating PKGBUILDs for existing `.deb` packages, correct? They can already be created manually today (see [the PKGBUILD for `element-desktop-bin`](https://mpr.makedeb.org/pkgbase/element-desktop-bin/git/tree/PKGBUILD)), it just doesn't have the ease of use you might find with Pacstall yet.

**Comment by hwittenborn** [comment]
makedeb extensions also haven't been finalized in their behavior yet, there might be a way to omit the `package()` function entirely in the future, I just haven't looked into it much yet.

**Comment by Elsie19** [comment]
> They can already be created manually

That's just uncompressing a deb and then makedeb builds it as a deb, which would remove all the maintainers for that particular debs work in making sure it's up to their standards.

**Comment by Heus-Sueh** [comment]
> It's a bit more than what you might have to type with something like Pacstall, but would that be acceptable for you? Or are you more so wanting the way Pacstall does it?> 

sorry for the late reply I was travelling, I think it would be better for mist to take care of it with: 
`mist install 'https://deb.librewolf.../librewolf.deb'` with some parameter maybe?
maybe a parameter for different distributions like: `mist install "source" --focal`
`--jammy`
`--focal`
`--bionic`
`--kinetic`
`--bullseye`
if you try to install a package made for `kinetic`, in ubuntu `bionic` the mist would block the installation


I just don't know how it will handle the dependencies of different versions of debian and ubuntu or if there is any way to identify the dependencies of a package and install it automatically for the user considering the different versions of ubuntu and debian
