### ISSUE TITLE
Add support for Mercurial Distributed SCM repositories. `hg`

### ISSUE THREAD

**Issue by Fijxu** [hwittenborn/makedeb#259]
### Description of feature

There is some AUR PKGBUILDs that use `hg` for the repositories like https://aur.archlinux.org/packages/nginx-quic

I wanted to port it to a DUR PKGBUILD (to use it on my server) but support for other VCS was removed in commit d1c9e8a and nobody complained about that since they are not widely used; But they are still important to easily maintain compatibility between AUR and DUR packages.

### Installed makedeb version

makedeb 6.0.0-stable

**Comment by hwittenborn** [comment]
Hey, thanks for reaching out!

Like you saw in that commit, things like Mercurial got their support in makedeb dropped a fair while ago. I'm not quite sure I'd want it added back - I know this example from the AUR highlights one, but I haven't seen many others (and considering it's been this long since an issue was found I'd care to think that things like Mercurial just aren't that popular).

If you have any points that you'd like to bring up to get Mercurial back in feel free to throw them out. As an immediate solution though, it looks like NGINX's Mercurial interface at least supports tar archives instead of directly using Mercurial clones (looking at the AUR PKGBUILD it looked like the corresponding tar URL is https://hg.nginx.org/nginx-quic/archive/91ad1abfb285.tar.gz). Would that work for your use case (including in a way that's satisfactory for you)?

**Comment by Fijxu** [comment]
So in the end i ported the Mercurial repo to a Git one and made a mirror of it for this ( https://mpr.makedeb.org/packages/nginx-quic ). But i still think that supporting other VCS that are not that widely used is still worth it to make it more easy to port them.
Thanks ;)

**Comment by hwittenborn** [comment]
The porting argument is definitely a good one - I think it might be worth looking into if some conversion tool could just do it automatically though.

I don't recall if I've ever seen you around in makedeb's support rooms, but there's plans to make a new tool from scratch, and such a tool is going to have a makedeb compatibility layer. There could also be a compatiblity layer for Arch-styled PKGBUILDs, and such a tool could just identify things like Git URLs and find a corresponding archive file, and then modify the `source` entries as needed.

Would something like that work for you? The archive files could then be used, but I don't know if that's acceptable for you regarding the then long-term maintainability of the new build file.
