### ISSUE TITLE
build dependency check fails when using `-F` argument

### ISSUE THREAD

**Issue by zocker-160** [hwittenborn/makedeb#30]
### Issue

when trying to run `makedeb -F DEBBUILD` the build dependency check fails because it apparently tried to run \
`cat: ./PKGBUILD` which does not exist, since I am using a different file name.

Far worse is when I acutally have a `PKGBUILD` (for AUR) next to my `DEBBUILD` file, it will silently pull the build dependencies from the wrong file.

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

6.3.3-1

### Installed makepkg version

8.5.0-1

**Comment by hwittenborn** [comment]
This appears to be due to [this line](https://github.com/makedeb/makedeb/blob/aea0f34474da50c2d9ae6456f594a85f3c26f914/src/functions/dependency_checks/check_dependencies.sh#L10) which has `PKGBUILD` hard-encoded without the ability to change. I should hopefully be able to get this fixed up tomorrow (I got to head to bed on my side real soon).

Just out of curiosity while I'm at it: Are you current having your `DEBBUILD` and `PKGBUILD` files side by side, or were you just providing an example?

**Comment by zocker-160** [comment]
> Are you current having your DEBBUILD and PKGBUILD files side by side, or were you just providing an example?

Yes I actually do have them side by side, because the dependencies for Arch and Debian / Ubuntu are different 
(I need `libnotify-bin` for Debian and `libnotify` for Arch)

PS: have you thought about changing the default filename to something different than `PKGBUILD`, since firstly you are not creating a PKG and secondly it will fail when trying to actually build a PKG with `makepkg`

**Comment by hwittenborn** [comment]
The fix for this should be deployed to all releases now.

> have you thought about changing the default filename to something different than `PKGBUILD`

Not much honestly, as makedeb originally used the exact same things makepkg used, just with all the conversion stuff on top. Changing to something like `DEBBUILD` would definitely be something I'd be open to throwing out there, but it would require some arguably big changes to things like the MPR where `PKGBUILD` is currently the default for all the packages. If that's something you'd really want, feel free to open another issue about it (gonna close this one since the original issue's solved).

**Comment by zocker-160** [comment]
`-F` works now as expected, thank you!

**Comment by hwittenborn** [comment]
Great, glad it works!

On a side note: I'm in the middle of writing up some people/organizations that are using makedeb to package for Debian-/Ubuntu-based systems. Would it be fine with you if I were to add your project to that list?

**Comment by zocker-160** [comment]
> Would it be fine with you if I were to add your project to that list?

Yeah sure no problem with that and I am going to put it on MPR in the coming days.

**Comment by hwittenborn** [comment]
Great, thanks a ton! :smiley:
