### ISSUE TITLE
Makedeb creates non-working deb file on Kali Linux

### ISSUE THREAD

**Issue by nweger** [hwittenborn/makedeb#31]
### Issue

I tried creating the deb file for kitty-bin in the newest version
I use Kali Linux, which uses kali-rolling as Codename, and as such the created deb had a non-working Depends section in the created deb

This is the error message I got when trying to install the created deb:

'Depends' field, invalid package name 'rolling_depends[@]': character '[' not allowed (only letters, digits and characters '-+._')

The provides, conflicts and replaces section had the same error

I edited the control file by hand after extracting the deb file, and then recreating it under a new name, and the Install worked

As requested, here is the Verbose Log: [verbose.log](https://github.com/makedeb/makedeb/files/7096238/verbose.log)

If anything else is needed, just tell me, I'll get it for you.

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

6.3.3-1

### Installed makepkg version

8.5.0-1

**Comment by hwittenborn** [comment]
So there's a few underlying issues with this that are going to need to be solved,

Since variables in Bash can't contain hyphens (`-`), it's tripping up and causing some *\*cough cough\** undocumented features.

Likewise, I need to figure out how to handle hyphens properly, with my first instinct being to just change them underscores (`_`; likewise `kali-rolling` would become `kali_rolling`).

The problem with that approach is that I'm them risking name conflicts (say there was another distro that used `kali_rolling` itself), and at that point I'd need to implement hacky workarounds that I would much rather not have to implement.

I'm gonna look into what systems could be implemented, or even possibly just getting Kali Linux to change the codename for their distribution (really pulling a stretch, but I really don't want to have hacky workarounds for things like this).

I'll keep this issue open until something is decided on, but until I can at least figure out an approach with people at Kali, this issue will probably just remain out in the open.

**Comment by nweger** [comment]
I just had an Idea.
Not sure if it's any good, but maybe you can actually parse the contents of /etc/os-release?

Debian itself has "ID=debian", and if that value is different you can use ID_LIKE?

I am pretty sure, that any Distro based on Debian has a variable in it that reads: "ID_LIKE=debian".

I just looked, and at least Kali has this, as does Ubuntu.

Maybe you can use that in some way?

**Comment by hwittenborn** [comment]
Well I need to use `VERSION_CODENAME` as I need the release name since things like Ubuntu 20.04 and 20.10 might have different dependencies.

Is there a string in there that you think might work?

**Comment by nweger** [comment]
Hm, sadly not really, but as I wrote, it was just an idea anyway.

But as to your idea with the underscore, I don't think that there would be another distro using kali_rolling as version codename.
I might be mistaken though.
I know that was just as an example, but would another distro use a version codename that similar to an existing one?
I for one, don't think so.

**Comment by hwittenborn** [comment]
> don't think that there would be another distro using kali_rolling as version codename. I might be mistaken though.

That's the main thing: kali_rolling was mostly just an example; I'm worried that there might be a different distro out there where that issue would arrise, or at the least one might pop up.

**Comment by nweger** [comment]
Maybe, but I don't really think that another distro would just use codenames that are that similar to other already existing distros.

And if they do, I would rather see it as a problem on the part of that other distro, and not really something you need to worry about?

But yeah, I do see your point.

**Comment by hwittenborn** [comment]
Well that's another thing, I somewhat feel like Kali Linux needs to solve this instead of me implementing a workaround. I get that the codename isn't exactly standardized (from what I've read), but Kali Linux appears to be the only distro with this kind of issue in its codename, so I'd much rather it be solved there.

If I can find more distros using a hyphen, I'd be glad to look more into implementing a workaround, but until then I'm really wanting this solved on Kali Linux's part.

**Comment by nweger** [comment]
Ah, okay, I was just typing anoither idea, that could maybe work?

--------

Oh, one other thing you could do, is just combine two different approaches and have something like "kali_kali_rolling_*"

where it would be the format: "\<distro\>\_\<codename\_with\_hyphens\_replaced\_if\_there\_are\_any\>\_*"?

Wouldn't that work?

**Comment by nweger** [comment]
But overall I'm okay with that approach :)

**Comment by hwittenborn** [comment]
That's just the hyphens-replaced-with-underscores approach, right?

**Comment by nweger** [comment]
Yeah, but with the Distro ID added in, which would make it unique enough?
But maybe that's just a dumb idea, I do have those from time to time :)

**Comment by hwittenborn** [comment]
Well I can't really change any existing prefixes as there's already some packages using them on the MPR (look at `discord` for an example).

It's definitely an approach, but it does feel quite hacky to me. Again, I'm **really** wanting this solved by Kali Linux going forward.

---

Assuming we did implement a workaround though, it would probably work like this:

1. Replace any existing underscores with double underscores (so `example_distro` would become `example__distro`).
2. Then, replace any hyphens with underscores (so `example-distro` becomes `example_distro`).

Likewise these examples would follow suit:

- `example--distro` -> `example__distro` (2 underscores)
- `example__distro` -> `example____distro` (4 underscores)
- `example-_distro` -> `example___distro` (3 underscores)

Doing some basic math, that is:

- 1 `-` == 1 `_`
- 1 `_` ==  2 `_`

And then just repeat for every occurrence of both characters.

That approach sounds quite fullproof to me (feel free to prove me wrong though), but again, it's a somewhat-hacky workaround, and I'd much rather just avoid implementing it and addressing the core issue directly.

**Comment by nweger** [comment]
Yeah, that's definitely something that should be fixed on Kali's part, but until that is fixed (if it ever will be) this should at least suffice as a stopgap :)

**Comment by hwittenborn** [comment]
I've gone ahead and made a post about the issue on their forum earlier today, I'm just awaiting a response to see how they'd like to go forward.

Sadly in the end Kali Linux isn't one of the "mainline" Debian-based distributions (and again, issue only appears to be present there), so there's less of a motivation to get it fixed for a small, minute amount of users.

If a lot of people using Kali Linux were to show up, then yeah, the need for it to be fixed natively would increase exponentially. But it doesn't appear to be so, so it's just a matter of waiting to see how to go forward.

**Comment by nweger** [comment]
Okay, I shall wait then :)

**Comment by nweger** [comment]
Just out of curiosity, where on their forum did you post?
I just had a look through it and did not find anything :)

**Comment by hwittenborn** [comment]
I'm pretty sure it's still awaiting approval by a moderator. Either that or the rejected it, but I'm highly doubting that happened.

**Comment by nweger** [comment]
Okay, thanks for all your help so far, I'll be going to bed for now, 4:23am here :)

**Comment by hwittenborn** [comment]
I can't remember the exact date it got done, but this got resolved [here](https://github.com/makedeb/makedeb/blob/stable/src/functions/dependency_checks/check_distro_dependencies.sh#L8) before the file got moved to a new location (looks like the commit has since been unmarked from the file, and I don't really want to do digging through the commit logs :P).

The current implementation will just abort if the distribution codename isn't a valid variable name instead of proceeding with checking distro dependencies. Sadly that means Kali Linux won't be able to actually utilize distro dependencies, but I don't see any other method currently that fits into avoiding anything that fits my definition of getting too hacky.

Feel free to comment if you have any comments or remaining issues.
