### ISSUE TITLE
makerpm -- possible?

### ISSUE THREAD

**Issue by sxiii** [hwittenborn/makedeb#86]
### Description of feature

Greetings dear makedeb team!

I wonder if it would be possible to add support to convert PKGBUILDs to RPMs (maybe via creating SRPMs + SPEC instructions first). Or if you know about such utility, could you please share a link or name?

Our purpose is to have one source PKGBUILD file for the required program(s); and then set up workflows so we could package:
* Debian packages
* RPM packages
* Arch original packages
All 3 types of packages built right from the same, single PKGBUILD file.

Would be really nice. Thanks a lot for your project & effort, very useful software.

### Installed makedeb version

makedeb 8.5.9-1

**Comment by hwittenborn** [comment]
Sadly I don't use any RPM-based distributions myself, so there's virtually no chance that I'd be able to support such a project reliably.

Maybe [fpm](https://github.com/jordansissel/fpm) could suit your needs? You'd need a separate tool for the Deb to RPM conversion, but afaik you wouldn't need any separate files for it or anything, though I haven't used the tool myself yet.

**Comment by lpuv** [comment]
hmm, could somehow integrate a tool called alien that converts deb files to rpm. I have used it before, not sure if it can be used with makedeb though

**Comment by hwittenborn** [comment]
Just remembered something I saw a while back - maybe [Pacur](https://github.com/pacur/pacur) can fill your needs? It appears to be using something close to a PKGBUILD spec.

**Comment by hwittenborn** [comment]
I'm thinking about this more, and I don't think there's much use in keeping the issue open, as it's not anything I plan on ever really implementing. I'm focusing on Deb based distros with makedeb, and it's just looking like it'll ever only be that just due to the integration I'm trying to create with it all with things like the MPR being present with it all.

Feel free to send another comment if you think there's something makedeb should do, but you should hopefully have a few recommendations if not as well.
